apiVersion: v1
kind: Namespace
metadata:
  name: test
spec:
  finalizers:
  - kubernetes
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi

